// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJK7IeinCTNa4W_UEijb8W_gc1jQfQjwk',
    appId: '1:1090065077764:web:5c017d27fad6a8815d4751',
    messagingSenderId: '1090065077764',
    projectId: 'tennis-ec27b',
    authDomain: 'tennis-ec27b.firebaseapp.com',
    storageBucket: 'tennis-ec27b.firebasestorage.app',
    measurementId: 'G-FGFEVD621H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMUsrS9R4VWQiEDmGApU7FQnI-k02aGo',
    appId: '1:1090065077764:android:182b27ebc9e6d9f75d4751',
    messagingSenderId: '1090065077764',
    projectId: 'tennis-ec27b',
    storageBucket: 'tennis-ec27b.firebasestorage.app',
  );

}